import { PlatformType, StreamStatus } from "@prisma/client"
import { NextResponse } from "next/server"

import { auth } from "@/auth"
import { addDestination } from "@/lib/egress"
import { prisma } from "@/lib/prisma"
import { rateLimitGuard, getClientIp } from "@/lib/rate-limit"
import { getCachedRoom } from "@/lib/room-cache"
import { publishEvent } from "@/lib/redis"

/**
 * F-24: host-triggered reconnect of a single platform destination that LiveKit
 * has marked FAILED on the active egress.
 *
 * Flow:
 *   1. Locate the active StreamSession for this room.
 *   2. Re-read the host's PlatformConnection for fresh stream key / ingest URL
 *      (the prior stream key may have been revoked / regenerated by the platform).
 *   3. Call LiveKit `updateStream(egressId, [url])` to re-add the destination.
 *   4. Publish STREAM_DESTINATION_CHANGED { action: "add" } so the host UI
 *      reflects the recovery, and the drop banner dismisses.
 *
 * Host-only. Rate-limited at "rooms:reconnect" (10/min/IP).
 */
export async function POST(req: Request, { params }: { params: Promise<{ code: string }> }) {
  const session = await auth()
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { code } = await params

  const blocked = await rateLimitGuard(getClientIp(req), "rooms:reconnect")
  if (blocked) return blocked

  // Body: { platform: "youtube" | "twitch" | "kick" | "tiktok" }
  let platform: string | null = null
  try {
    const body = await req.json()
    if (typeof body?.platform === "string") platform = body.platform.toLowerCase().trim()
  } catch {
    /* empty body */
  }
  if (!platform) {
    return NextResponse.json({ error: "Missing platform" }, { status: 400 })
  }

  const room = await getCachedRoom(code)
  if (!room || room.hostId !== session.user.id) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 })
  }

  // Find active egress for this room.
  const activeSession = await prisma.streamSession.findFirst({
    where: { roomId: room.id, status: { in: [StreamStatus.STARTING, StreamStatus.LIVE] } },
    orderBy: { startedAt: "desc" },
  })
  if (!activeSession?.egressId) {
    return NextResponse.json({ error: "No active stream to reconnect" }, { status: 409 })
  }

  // Validate platform + lookup PlatformConnection for fresh stream key.
  const dbPlatform = platform.toUpperCase() as PlatformType
  if (!Object.values(PlatformType).includes(dbPlatform)) {
    return NextResponse.json({ error: "Unknown platform" }, { status: 400 })
  }
  const connection = await prisma.platformConnection.findUnique({
    where: { userId_platform: { userId: session.user.id, platform: dbPlatform } },
  })
  if (!connection?.streamKey) {
    return NextResponse.json(
      { error: "Stream key missing for platform — open Settings to reconnect", platform },
      { status: 409 },
    )
  }

  try {
    await addDestination(
      activeSession.egressId,
      dbPlatform,
      connection.streamKey,
      connection.ingestUrl,
    )
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : "Unknown egress error"
    console.error(`[stream-live/reconnect] Failed to re-add ${platform}:`, err)
    return NextResponse.json(
      { error: "Reconnect failed", details: errorMessage },
      { status: 502 },
    )
  }

  // Update the persisted destination set so a later GET /platforms or PATCH
  // remove gets the right starting state.
  const updatedPlatforms = Array.from(new Set([...activeSession.platforms, dbPlatform]))
  await prisma.streamSession.update({
    where: { id: activeSession.id },
    data: { platforms: updatedPlatforms },
  })

  await publishEvent(code, {
    type: "STREAM_DESTINATION_CHANGED",
    data: { action: "add", platform: dbPlatform },
  })

  return NextResponse.json({ ok: true, platform })
}
